### ISSUE TITLE
Tracker: Release 0.6-beta

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#132]
Items left to do for `0.6-beta` release:

* [x] Update version numbers in:
    * [x] README.md
    * [x] lib.rs
* [x] Push to crates.io
* [x] Write release notes on:
    * [x] Github Releases
    * [x] users.rust-lang.org 

Same steps have to be repeated for stable `0.6` release

**Comment by Dylan-DPC** [comment]
Users forum post: https://users.rust-lang.org/t/uuid-crate-is-back/15507
