### ISSUE TITLE
Tracker: Release 0.6

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#140]
Items left to do for `0.6` release:

* [x] Update version numbers in:
    * [x] README.md
    * [x] lib.rs
* [x] Push to crates.io
* [x] Write release notes on:
    * [x] Github Releases
    * [x] users.rust-lang.org

**Comment by Dylan-DPC** [comment]
Users forum post: https://users.rust-lang.org/t/uuid-0-6-0-is-released/15683
