### ISSUE TITLE
Release 0.6.1

### ISSUE THREAD

**Issue by Dylan-DPC** [uuid-rs/uuid#160]
Items left to do for 0.6.1 release:

* [x] Update version numbers in:
    * [x] ~~lib.rs~~
    * [x] Cargo.toml
* [xt] Push to crates.io
* [x] Write release notes on:
    * [x] Github Releases
    * [x] users.rust-lang.org

**Comment by kinggoesgaming** [comment]
Published!
