### ISSUE TITLE
Tracker: 0.6.2

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#179]
Items left to do for __*0.6.2*__ release:

* [x] Update version numbers
* [x] Push to crates.io
* [x] Write release notes on:
    * [x] Github Releases
    * [x] users.rust-lang.org

**Comment by Dylan-DPC** [comment]
:tada: Released :tada:
