### ISSUE TITLE
Release: 0.6.3

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#194]
Items left to do for __*0.6.3*__ release:

* [x] Update version numbers
* [x] Push to crates.io
* [x] Write release notes on:
    * [x] Github Releases
    * [x] users.rust-lang.org

**Comment by kinggoesgaming** [comment]
published!
