### ISSUE TITLE
Upgrade minimum rust version

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#230]
#143 set the minimum rust version to `1.18.0`. I think its time we start on bumping the version

Tasks to do:
* [ ] Check all the dependent crates' minimum rust versions.
  * Eliminate all crates that crates that don't specify a minimum version.
* [ ] Eliminate crates that have not yet reached `1.0`
* [ ] Determine path of upgrade

**Comment by Dylan-DPC** [comment]
>  Eliminate crates that have not yet reached 1.0

Is there a reason for this? I think it is fine to depend on crates that haven't reached 1.0. It is a good rule but we shouldn't be strict on it.

**Comment by KodrAus** [comment]
@Dylan-DPC I think this is part of a process for figuring out what the minimum versions of dependents of `uuid` are.

As for our minimum version policy, I think it makes sense to be conservative, since `uuid` is widely depended on. So for `uuid` with just `v1`, `v3`, `v4`, `v5` features we should probably target the lowest version we can and stick with it. We've got feature gates for newer things so dependents can opt in to more recent compilers.

**Comment by KodrAus** [comment]
Bumping to `1.22` seems reasonable to me, it should be accessible to most folks through package managers. We might want to wait until the next breaking release of `uuid` though since it's pretty widely used.

**Comment by Dylan-DPC** [comment]
@KodrAus yah that's the plan to update it for 0.7.0 release
