### ISSUE TITLE
0.7.0-beta release

### ISSUE THREAD

**Issue by Dylan-DPC** [uuid-rs/uuid#306]
Items left to do for __*0.7.0-beta*__ release:

* [x] Update version numbers
* [x] Push to crates.io
* [x] Write release notes on:
    * [x] Github Releases
    * [x] users.rust-lang.org
    * [x] uuid-rs mailing list

**Comment by Dylan-DPC** [comment]
Users' Forum: https://users.rust-lang.org/t/announcing-uuid-0-7-0-beta/19835

**Comment by kinggoesgaming** [comment]
https://uuid-rs.groups.io/g/main/message/5
