### ISSUE TITLE
Tracker: 0.7.0

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#313]
Items left to do for __*0.7.0*__ release:

* [x] Update version numbers
* [x] Push to crates.io
* [x] Write release notes on:
    * [x] Github Releases
    * [x] users.rust-lang.org
    * [x] mailing list

**Comment by kinggoesgaming** [comment]
release notes list updated: 

https://github.com/uuid-rs/uuid/pulls?q=is%3Apr+is%3Aclosed+milestone%3A0.7.0+label%3A%22Release+Notes%22
