### ISSUE TITLE
Tracker: 0.7.1 release

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#318]
Items left to do for __*0.7.1*__ release:

* [x] Update version numbers
* [x] Push to crates.io
* [x] Write release notes on:
    * [x] Github Releases
    * [x] users.rust-lang.org
    * [ ] mailing list

**Comment by kinggoesgaming** [comment]
https://uuid-rs.groups.io/g/main/message/8
