### ISSUE TITLE
Tracker: 0.7.3 release

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#381]
Items left to do for __*0.7.3*__ release:

* [x] Update version numbers
* [x] Push to crates.io
* [x] Write release notes on:
    * [x] Github Releases
    * [x] users.rust-lang.org
